import "./loadEnv"; // must be first: loads keys before clients are built
import { readFile } from "node:fs/promises";
import { embedAndCompress, embedDedup, embeddingInput } from "../lib/embeddings/embed";
import { insertQuestions, type QuestionSeed } from "../lib/db/questions";
import { inBatchDuplicates, findExistingDuplicate } from "../lib/db/dedup";
import { validateAuthoredQuestion } from "../lib/questions/validate";
import { sql } from "../lib/db/client";

// Import trivia questions authored by a Haiku subagent straight into Supabase.
// The ONLY API call here is the embedding (OpenAI); the questions themselves are
// authored by the subagent, not generated by an API call.
//
// Usage: npx tsx scripts/insert-authored.ts <path-to-json>
// where the JSON is an array of { text, choices[4], correctIndex, difficulty }.

type Authored = {
  text: string;
  choices: string[];
  correctIndex: number;
  difficulty: number;
};

async function main() {
  const path = process.argv[2];
  if (!path) {
    console.error("usage: npx tsx scripts/insert-authored.ts <path-to-json>");
    process.exit(1);
  }

  const raw = JSON.parse(await readFile(path, "utf8")) as Authored[];
  // Structural + quality gate. A non-null reason (malformed, or a stem that
  // gives away its own answer) drops the question and logs why.
  const valid = raw.filter((q, i) => {
    const reason = validateAuthoredQuestion(q);
    if (reason) console.warn(`Dropped question #${i} — ${reason}`);
    return reason === null;
  });
  if (valid.length !== raw.length) {
    console.warn(`Dropped ${raw.length - valid.length} question(s) total.`);
  }
  if (valid.length === 0) {
    console.error("No valid questions to insert.");
    await sql.end();
    process.exit(1);
  }

  // The one allowed API call: embed stem + correct answer. We build TWO vectors
  // from the same text — the 64-D recommendation vector and the 256-D dedup
  // vector (migration 0014).
  const inputs = valid.map(embeddingInput);
  const [embeddings, dedupVecs] = await Promise.all([
    embedAndCompress(inputs),
    embedDedup(inputs),
  ]);

  // Near-duplicate gate (double lever — see lib/db/dedup.ts). A candidate is
  // dropped when its nearest match — an earlier candidate in THIS file, or
  // something already in the bank — is close enough in the 256-D space, with a
  // softer cutoff when the correct answers also match.
  const answers = valid.map((q) => q.choices[q.correctIndex]);
  const droppedInBatch = inBatchDuplicates(dedupVecs, answers);
  const seeds: QuestionSeed[] = [];
  let skippedBatch = 0;
  let skippedBank = 0;

  for (let i = 0; i < valid.length; i++) {
    const q = valid[i];

    const twin = droppedInBatch.get(i);
    if (twin !== undefined) {
      skippedBatch++;
      console.warn(
        `Skipped (dup of earlier in file): "${q.text}"\n    ~= "${valid[twin].text}"`,
      );
      continue;
    }

    const hit = await findExistingDuplicate(dedupVecs[i], answers[i]);
    if (hit) {
      skippedBank++;
      console.warn(
        `Skipped (dup of existing, sim ${hit.sim.toFixed(3)}): "${q.text}"\n    ~= "${hit.text}"`,
      );
      continue;
    }

    seeds.push({
      text: q.text,
      choices: q.choices,
      correctIndex: q.correctIndex,
      difficulty: q.difficulty,
      embedding: embeddings[i],
      embedding256: dedupVecs[i],
    });
  }

  const n = await insertQuestions(seeds);
  console.log(
    `Inserted ${n} questions from ${path} ` +
      `(skipped ${skippedBatch} in-file dup(s), ${skippedBank} existing dup(s)).`,
  );
  await sql.end();
}

main().catch(async (err) => {
  console.error(err);
  await sql.end();
  process.exit(1);
});
