import "./loadEnv"; // must be first: loads keys before clients are built
import { readFile } from "node:fs/promises";
import { embedAndCompress, embeddingInput } from "../lib/embeddings/embed";
import { insertQuestions, type QuestionSeed } from "../lib/db/questions";
import { validateAuthoredQuestion } from "../lib/questions/validate";
import { sql } from "../lib/db/client";

// Import trivia questions authored by a Haiku subagent straight into Supabase.
// The ONLY API call here is the embedding (OpenAI); the questions themselves are
// authored by the subagent, not generated by an API call.
//
// Usage: npx tsx scripts/insert-authored.ts <path-to-json>
// where the JSON is an array of { text, choices[4], correctIndex, difficulty }.

type Authored = {
  text: string;
  choices: string[];
  correctIndex: number;
  difficulty: number;
};

async function main() {
  const path = process.argv[2];
  if (!path) {
    console.error("usage: npx tsx scripts/insert-authored.ts <path-to-json>");
    process.exit(1);
  }

  const raw = JSON.parse(await readFile(path, "utf8")) as Authored[];
  // Structural + quality gate. A non-null reason (malformed, or a stem that
  // gives away its own answer) drops the question and logs why.
  const valid = raw.filter((q, i) => {
    const reason = validateAuthoredQuestion(q);
    if (reason) console.warn(`Dropped question #${i} — ${reason}`);
    return reason === null;
  });
  if (valid.length !== raw.length) {
    console.warn(`Dropped ${raw.length - valid.length} question(s) total.`);
  }
  if (valid.length === 0) {
    console.error("No valid questions to insert.");
    await sql.end();
    process.exit(1);
  }

  // The one allowed API call: embed stem + correct answer, compress to 64-D.
  const embeddings = await embedAndCompress(valid.map(embeddingInput));
  const seeds: QuestionSeed[] = valid.map((q, i) => ({
    text: q.text,
    choices: q.choices,
    correctIndex: q.correctIndex,
    difficulty: q.difficulty,
    embedding: embeddings[i],
  }));

  const n = await insertQuestions(seeds);
  console.log(`Inserted ${n} questions from ${path}.`);
  await sql.end();
}

main().catch(async (err) => {
  console.error(err);
  await sql.end();
  process.exit(1);
});
